FROM tensorflow/tensorflow:2.6.0

RUN apt-get update && apt-get install -y

RUN pip install --upgrade pip

RUN pip install torch

RUN pip install transformers

RUN pip install sentencepiece

WORKDIR /app

COPY . .

CMD ["python", "main.py"]